clean:
	-rm -f core *.o main

aula1:
	g++ -o main aula1.cpp   -lGL -lGLU -lglut

aula2:
	g++ -o main aula2.cpp   -lGL -lGLU -lglut

aula3:
	g++ -o main aula3.cpp  -lGL -lGLU -lglut

pong:
	g++ -o main pong.cpp  -lGL -lGLU -lglut

aula3D:
	g++ -o main aula3D.cpp  -lGL -lGLU -lglut

myglu:
	g++ -o main myGluLookAtExample.cpp  -lGL -lGLU -lglut
